# 📊 Olist — Sales & Delivery Analysis

**Dataset:** Brazilian E-Commerce (Olist, 2016–2018)  
**Tablas:** `orders`, `customers`, `payments`  
**Objetivo:** Análisis de rendimiento de entregas y comportamiento de pagos

---

## Setup

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

# Cambia 'tu_usuario' por tu usuario de Mac
%sql postgresql://tomas@localhost:5432/data_engineering

---
## 1. Overview del dataset

In [2]:
%%sql
-- Volumen general por tabla
SELECT 'orders'    AS tabla, COUNT(*) AS filas FROM orders
UNION ALL
SELECT 'customers' AS tabla, COUNT(*) AS filas FROM customers
UNION ALL
SELECT 'payments'  AS tabla, COUNT(*) AS filas FROM payments;

       tabla   filas
0   payments  103886
1  customers   99441
2     orders   96478

In [ ]:
%%sql
-- Ver columnas y tipos de la tabla orders
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'orders'
ORDER BY ordinal_position;*

In [3]:
%%sql
-- Rango temporal del dataset
SELECT
    MIN(order_purchase_timestamp) AS primer_pedido,
    MAX(order_purchase_timestamp) AS ultimo_pedido
FROM orders;

        primer_pedido       ultimo_pedido
0 2016-09-15 12:16:38 2018-08-29 15:00:37

---
## 2. Análisis de entregas

In [4]:
%%sql
-- Distribución de tiempos de entrega
SELECT
    COUNT(*)                                        AS total_pedidos,
    ROUND(AVG(delivery_days)::numeric, 1)           AS media_dias,
    PERCENTILE_CONT(0.5) WITHIN GROUP
        (ORDER BY delivery_days)                    AS mediana_dias,
    MIN(delivery_days)                              AS min_dias,
    MAX(delivery_days)                              AS max_dias
FROM orders;

   total_pedidos media_dias  mediana_dias  min_dias  max_dias
0          96478       12.1          10.0       0.0     209.0

In [5]:
%%sql
-- Pedidos agrupados por rango de días de entrega
SELECT
    CASE
        WHEN delivery_days = 0        THEN '0 días (mismo día)'
        WHEN delivery_days BETWEEN 1 AND 7   THEN '1-7 días'
        WHEN delivery_days BETWEEN 8 AND 14  THEN '8-14 días'
        WHEN delivery_days BETWEEN 15 AND 30 THEN '15-30 días'
        ELSE '+ 30 días'
    END AS rango_entrega,
    COUNT(*) AS total,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 1) AS porcentaje
FROM orders
GROUP BY rango_entrega
ORDER BY MIN(delivery_days);

        rango_entrega  total porcentaje
0  0 días (mismo día)     13        0.0
1            1-7 días  33683       34.9
2           8-14 días  36397       37.7
3          15-30 días  22260       23.1
4           + 30 días   4125        4.3

In [6]:
%%sql
-- Top 10 ciudades con más pedidos y su media de entrega
-- JOIN entre orders y customers por customer_id
SELECT
    c.customer_city                                 AS ciudad,
    COUNT(*)                                        AS total_pedidos,
    ROUND(AVG(o.delivery_days)::numeric, 1)         AS media_dias_entrega
FROM orders o
LEFT JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_city
ORDER BY total_pedidos DESC
LIMIT 10;

                  ciudad  total_pedidos media_dias_entrega
0              sao paulo          15045                7.6
1         rio de janeiro           6601               14.3
2         belo horizonte           2697               10.7
3               brasilia           2071               12.5
4               curitiba           1489               10.0
5               campinas           1406                9.4
6           porto alegre           1342               15.5
7               salvador           1188               18.9
8              guarulhos           1144                7.5
9  sao bernardo do campo            911                7.6

In [7]:
%%sql
-- Estados con peor tiempo medio de entrega (mínimo 100 pedidos)
SELECT
    c.customer_state                                AS estado,
    COUNT(*)                                        AS total_pedidos,
    ROUND(AVG(o.delivery_days)::numeric, 1)         AS media_dias_entrega
FROM orders o
LEFT JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_state
HAVING COUNT(*) >= 100
ORDER BY media_dias_entrega DESC
LIMIT 10;

  estado  total_pedidos media_dias_entrega
0     AM            145               26.0
1     AL            397               24.0
2     PA            946               23.3
3     MA            717               21.1
4     SE            335               21.0
5     CE           1279               20.8
6     PB            517               20.0
7     PI            476               19.0
8     RO            243               18.9
9     BA           3256               18.9

---
## 3. Análisis de pagos

In [8]:
%%sql
-- Distribución por método de pago
SELECT
    payment_type                                    AS metodo_pago,
    COUNT(*)                                        AS total_transacciones,
    ROUND(AVG(payment_value)::numeric, 2)           AS valor_medio,
    ROUND(SUM(payment_value)::numeric, 2)           AS valor_total
FROM payments
GROUP BY payment_type
ORDER BY total_transacciones DESC;

   metodo_pago  total_transacciones valor_medio  valor_total
0  credit_card                76795      163.32  12542084.19
1       boleto                19784      145.03   2869361.27
2      voucher                 5775       65.70    379436.87
3   debit_card                 1529      142.57    217989.79
4  not_defined                    3        0.00         0.00

In [9]:
%%sql
-- Pedidos con múltiples métodos de pago
SELECT
    COUNT(*) AS total_pagos,
    payment_installments AS cuotas,
    ROUND(AVG(payment_value)::numeric, 2) AS valor_medio
FROM payments
GROUP BY payment_installments
ORDER BY cuotas;

    total_pagos  cuotas valor_medio
0             2       0       94.32
1         52546       1      112.42
2         12413       2      127.23
3         10461       3      142.54
4          7098       4      163.98
5          5239       5      183.47
6          3920       6      209.85
7          1626       7      187.67
8          4268       8      307.74
9           644       9      203.44
10         5328      10      415.09
11           23      11      124.93
12          133      12      321.68
13           16      13      150.46
14           15      14      167.96
15           74      15      445.55
16            5      16      292.69
17            8      17      174.60
18           27      18      486.48
19           17      20      615.80
20            3      21      243.70
21            1      22      228.71
22            1      23      236.48
23           18      24      610.05

In [11]:
%%sql
-- Pedidos agrupados por número de cuotas
SELECT
    payment_installments AS cuotas,
    COUNT(*) AS total_pagos,
    ROUND(AVG(payment_value)::numeric, 2) AS valor_medio
FROM payments
GROUP BY payment_installments
ORDER BY cuotas;

    cuotas  total_pagos valor_medio
0        0            2       94.32
1        1        52546      112.42
2        2        12413      127.23
3        3        10461      142.54
4        4         7098      163.98
5        5         5239      183.47
6        6         3920      209.85
7        7         1626      187.67
8        8         4268      307.74
9        9          644      203.44
10      10         5328      415.09
11      11           23      124.93
12      12          133      321.68
13      13           16      150.46
14      14           15      167.96
15      15           74      445.55
16      16            5      292.69
17      17            8      174.60
18      18           27      486.48
19      20           17      615.80
20      21            3      243.70
21      22            1      228.71
22      23            1      236.48
23      24           18      610.05

---
## 4. JOINs combinados — Orders + Customers + Payments

In [10]:
%%sql
-- Valor medio de pedido por estado, con tiempo de entrega
-- Triple JOIN: orders → customers → payments
SELECT
    c.customer_state                                AS estado,
    COUNT(DISTINCT o.order_id)                      AS total_pedidos,
    ROUND(AVG(o.delivery_days)::numeric, 1)         AS media_dias_entrega,
    ROUND(AVG(p.payment_value)::numeric, 2)         AS valor_medio_pedido
FROM orders o
LEFT JOIN customers c ON o.customer_id = c.customer_id
LEFT JOIN payments p  ON o.order_id   = p.order_id
GROUP BY c.customer_state
ORDER BY total_pedidos DESC;

   estado  total_pedidos media_dias_entrega valor_medio_pedido
0      SP          40501                8.3             136.39
1      RJ          12350               14.9             158.08
2      MG          11354               11.5             154.12
3      RS           5345               14.8             155.45
4      PR           4923               11.6             152.45
5      SC           3546               14.5             162.58
6      BA           3256               18.8             169.76
7      DF           2080               12.5             161.60
8      ES           1995               15.4             153.62
9      GO           1957               15.1             163.31
10     PE           1593               18.0             185.41
11     CE           1279               20.7             198.71
12     PA            946               23.3             216.13
13     MT            886               17.6             199.61
14     MA            717               21.2             201.10
15     MS            701               15.2             186.18
16     PB            517               20.0             250.15
17     PI            476               19.0             208.87
18     RN            474               19.2             197.12
19     AL            397               24.2             229.19
20     SE            335               20.9             204.33
21     TO            274               16.9             203.41
22     RO            243               18.9             226.99
23     AM            145               26.1             182.76
24     AC             80               20.4             235.98
25     AP             67               26.7             233.94
26     RR             41               29.0             220.48

---
## 5. Windows Function

> Añade aquí tus propias queries de análisis.

In [2]:
%%sql
-- Ranking de pedidos por tiempo de entrega dentro de cada ciudad
-- ROW_NUMBER asigna 1 al más rápido, 2 al segundo más rápido, etc.
SELECT
    order_id,
    customer_id,
    delivery_days,
    ROW_NUMBER() OVER (ORDER BY delivery_days ASC) AS ranking_global
FROM orders
LIMIT 20;

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

,order_id,customer_id,delivery_days,ranking_global
0,d3ca7b82c922817b06e5ca21165c5ea2,d23df2c6c3e51d875f458d123b2b3c90,0.0,1
1,38c1e3d4ed6a13cd0cf612d4c09766e9,18c934f4cdc994cd04eb13bce3f47a18,0.0,2
2,b70a8d75313560b4acf607739560a0e5,42992f7eb57b0f04f5a52cf89112f415,0.0,3
3,8339b608be0d84fca9d8da68b58332c3,ff58662c328f81d3ee549c9caa942f39,0.0,4
4,e65f1eeee1f52024ad1dcd03447f7482,198f511b5a75bf936a96f1d4769e3974,0.0,5
5,1d893dd7ca5f77ebf5f59f0d2017eee0,b19da0df0271e8a3553e3670f86aeab5,0.0,6
6,79e324907160caea526fd8b94389dbbc,331d79b67223ee7e5cd31d3e03e4cfcc,0.0,7
7,f3c6775ba3d2d9fe2826f93b71f12008,6aef84c09844a371d82a49152c550b95,0.0,8
8,434cecee7d1a65fc65358a632b6f725f,922a46283625e9c096bfd998913c470c,0.0,9
9,f349cdb62f69c3fae5c4d7d3f3a4a185,c5e200d485ae35a7036cc2e7c1d8ea81,0.0,10
10,21a8ffca665bc7a1087d31751a7b7cbc,225aed9e773953084b09cf496c2be05a,0.0,11
11,bb5a519e352b45b714192a02ffe25681,118295a853acb536efff13740faf5be8,0.0,12
12,d5fbeedc85190ba88580d6f82d1d5ed3,344423c2e26d47d2b6d3dd363a89e812,0.0,13
13,b1e3487949a5a179250f5e81214578e6,9a63460fe86a248fb211087b0f9d6945,1.0,14
14,a3df9ee0e0290b6eb2d3abb966d5346f,23a449ad84ad098c509b42c8005f2e2b,1.0,15
15,c94047ec162181b78322184f7a9aee43,d4f243fba8f7e8213c43f98eb04b6213,1.0,16
16,d884c6a73ee6bc49e4db45abae4f3490,2c8db57d87eae06ab00d1ec167f43324,1.0,17
17,0e082c9595209f2c00439a05c63561fb,ed6fcc0b293e7864b2713bdefd4fd460,1.0,18
18,078db7c551c5b6a107ba6d586a13f14d,04e93f286b7920c82dc1a31240255ee6,1.0,19
19,ca65e3c6e57d9268c00fd2a65cbd14d0,3ba2431d39a1755e6f02841aec4c098f,1.0,20

In [4]:
%%sql
-- Ranking de pedidos por tiempo de entrega DENTRO de cada ciudad
-- PARTITION BY reinicia el contador en cada ciudad
SELECT
    o.order_id,
    c.customer_city,
    o.delivery_days,
    ROW_NUMBER() OVER (
        PARTITION BY c.customer_city
        ORDER BY o.delivery_days ASC
    ) AS ranking_en_ciudad
FROM orders o
LEFT JOIN customers c ON o.customer_id = c.customer_id
LIMIT 30;

,order_id,customer_city,delivery_days,ranking_en_ciudad
0,d99e6849f7676dade195f20c26f0eb4f,abadia dos dourados,5.0,1
1,0a9a43ac5fe59c6c4bee2a8f9b9fcce8,abadia dos dourados,8.0,2
2,50ba38c4dc467baab1ea2c8c7747934d,abadia dos dourados,21.0,3
3,3f1294f87d79b57f5d55ba7b80c3d94f,abadiania,29.0,1
4,6c12feac9a308e1382d9b19cca7f20b2,abaete,4.0,1
5,4ccc4e96e0fa5c35efbf9bf836ebef72,abaete,7.0,2
6,807756ebd577f025334944b87da7dbc3,abaete,7.0,3
7,1c2f555edfc445e72867c301b68ac512,abaete,7.0,4
8,74bdc516d1c6a8e16cd1a546ea067c26,abaete,7.0,5
9,5525ea8ee9e6150faa9b41dfc4024552,abaete,8.0,6
10,902864b6c62e404e8a57ca48c90657e8,abaete,8.0,7
11,ee2b11b5601e9de355fb771525a195ce,abaete,10.0,8
12,eb2eb20abe0258707c152cc393dfcb16,abaete,11.0,9
13,2eecb0d85f281280f79fa00f9cec1a95,abaete,13.0,10
14,3f6833af28b1e2885b8df4899e9aa8d1,abaete,14.0,11
15,33d425553bc88c255ddeb68ab933167e,abaete,23.0,12
16,57d0f29d2d770802ab8e393778fc9052,abaetetuba,10.0,1
17,fbb38f33f44df110ef060767b70bdfa3,abaetetuba,14.0,2
18,8a170c32858870f69d7a3477fcca9a4b,abaetetuba,15.0,3
19,56203d7ad8ce86a53281778d2dd2c9b7,abaetetuba,15.0,4
20,416481e8a5f360245c85849645837e6b,abaetetuba,17.0,5
21,679783b320e587d8e1c9e0dcb2421539,abaetetuba,18.0,6
22,d002a94b221c08e6dd8ed72e7662d31d,abaetetuba,31.0,7
23,be898fe8e3213cd0d57464c0b1284b99,abaetetuba,34.0,8
24,b3e86749e6dd7b4df4f345abbd329912,abaetetuba,40.0,9
25,38dcb5499d8854b4b2c6dbaaf983f21e,abaetetuba,48.0,10
26,210815e915694747f4d7f75010d5a665,abaetetuba,50.0,11
27,73ffc468078b5f3e2c4260065e5e5152,abaiara,25.0,1
28,9b189f6cf2ef734a7dd0419ed3c64d99,abaiara,45.0,2
29,0ae45a816351887a536ef37fd5fd9853,abaira,14.0,1

In [6]:
%%sql
-- Dame el pedido más rápido de cada ciudad
WITH pedidos_ranked AS (
    -- Aquí va una query COMPLETA
    SELECT
        o.order_id,
        c.customer_city,
        o.delivery_days,
        ROW_NUMBER() OVER (
            PARTITION BY c.customer_city
            ORDER BY o.delivery_days ASC
        ) AS ranking_en_ciudad
    FROM orders o
    LEFT JOIN customers c ON o.customer_id = c.customer_id
)
SELECT *
FROM pedidos_ranked
WHERE ranking_en_ciudad = 1;

,order_id,customer_city,delivery_days,ranking_en_ciudad
0,d99e6849f7676dade195f20c26f0eb4f,abadia dos dourados,5.0,1
1,3f1294f87d79b57f5d55ba7b80c3d94f,abadiania,29.0,1
2,6c12feac9a308e1382d9b19cca7f20b2,abaete,4.0,1
3,57d0f29d2d770802ab8e393778fc9052,abaetetuba,10.0,1
4,73ffc468078b5f3e2c4260065e5e5152,abaiara,25.0,1
...,...,...,...,...
4080,26968873aef9380ae17bfc3717c8cd7d,xinguara,12.0,1
4081,9053095d6a8816107d406e70df00efd0,xique-xique,15.0,1
4082,388a9117213936e0290e6e7d50f9fee0,zacarias,9.0,1
4083,fa1a82991080d1ed588c811aa7e8fdb6,ze doca,14.0,1
4084,bfc66aaefcaf92d4f853576104191c8d,zortea,12.0,1

In [10]:
%%sql
-- Los 3 pedidos más lentos de cada estado
WITH pedidos_ranked AS (
    -- Aquí va una query COMPLETA
    SELECT
        o.order_id,
        c.customer_state,
        o.delivery_days,
        ROW_NUMBER() OVER (
            PARTITION BY c.customer_state
            ORDER BY o.delivery_days DESC NULLS LAST
        ) AS ranking_en_estado
    FROM orders o
    LEFT JOIN customers c ON o.customer_id = c.customer_id
)
SELECT *
FROM pedidos_ranked
WHERE ranking_en_estado <= 3;

,order_id,customer_state,delivery_days,ranking_en_estado
0,0b7cb1c7ea62d95ba39702f4ae850108,AC,72.0,1
1,2bcf1f79964f8b4f4f62f19441601b1a,AC,66.0,2
2,ca2c921a5b9d60eba417d106c724c6f6,AC,42.0,3
3,d573a47c29466bb2e4e46aef0ff04f23,AL,90.0,1
4,ae213a9f84c777fb7a31e8c0f09fd30c,AL,77.0,2
...,...,...,...,...
76,2fe324febf907e3ea3f2aa9650869fa5,SP,189.0,2
77,d24e8541128cea179a11a65176e0a96f,SP,175.0,3
78,f5691c2b1ca263490374d13d020bd950,TO,58.0,1
79,1734eb8be40c91938e56f9d245b636a5,TO,44.0,2
80,2049616726f9272f1d1456285ad13cf5,TO,41.0,3

In [11]:
%%sql
-- Evolución mensual de pedidos con comparación al mes anterior
WITH pedidos_por_mes AS (
    SELECT
        DATE_TRUNC('month', order_purchase_timestamp) AS mes,
        COUNT(*) AS total_pedidos
    FROM orders
    GROUP BY mes
    ORDER BY mes
)
SELECT
    mes,
    total_pedidos,
    LAG(total_pedidos) OVER (ORDER BY mes) AS pedidos_mes_anterior,
    total_pedidos - LAG(total_pedidos) OVER (ORDER BY mes) AS diferencia
FROM pedidos_por_mes;

          mes  total_pedidos  pedidos_mes_anterior  diferencia
0  2016-09-01              1                   NaN         NaN
1  2016-10-01            265                   1.0       264.0
2  2016-12-01              1                 265.0      -264.0
3  2017-01-01            750                   1.0       749.0
4  2017-02-01           1653                 750.0       903.0
5  2017-03-01           2546                1653.0       893.0
6  2017-04-01           2303                2546.0      -243.0
7  2017-05-01           3546                2303.0      1243.0
8  2017-06-01           3135                3546.0      -411.0
9  2017-07-01           3872                3135.0       737.0
10 2017-08-01           4193                3872.0       321.0
11 2017-09-01           4150                4193.0       -43.0
12 2017-10-01           4478                4150.0       328.0
13 2017-11-01           7289                4478.0      2811.0
14 2017-12-01           5513                7289.0     -1776.0
15 2018-01-01           7069                5513.0      1556.0
16 2018-02-01           6555                7069.0      -514.0
17 2018-03-01           7003                6555.0       448.0
18 2018-04-01           6798                7003.0      -205.0
19 2018-05-01           6749                6798.0       -49.0
20 2018-06-01           6099                6749.0      -650.0
21 2018-07-01           6159                6099.0        60.0
22 2018-08-01           6351                6159.0       192.0

In [12]:
%%sql
-- Diferencia entre ROW_NUMBER, RANK y DENSE_RANK
-- Usamos delivery_days para ver cómo tratan los empates
SELECT
    order_id,
    delivery_days,
    ROW_NUMBER()  OVER (ORDER BY delivery_days ASC NULLS LAST) AS row_number,
    RANK()        OVER (ORDER BY delivery_days ASC NULLS LAST) AS rank,
    DENSE_RANK()  OVER (ORDER BY delivery_days ASC NULLS LAST) AS dense_rank
FROM orders
LIMIT 20;

,order_id,delivery_days,row_number,rank,dense_rank
0,f349cdb62f69c3fae5c4d7d3f3a4a185,0.0,1,1,1
1,d3ca7b82c922817b06e5ca21165c5ea2,0.0,2,1,1
2,38c1e3d4ed6a13cd0cf612d4c09766e9,0.0,3,1,1
3,e65f1eeee1f52024ad1dcd03447f7482,0.0,4,1,1
4,434cecee7d1a65fc65358a632b6f725f,0.0,5,1,1
5,f3c6775ba3d2d9fe2826f93b71f12008,0.0,6,1,1
6,bb5a519e352b45b714192a02ffe25681,0.0,7,1,1
7,b70a8d75313560b4acf607739560a0e5,0.0,8,1,1
8,21a8ffca665bc7a1087d31751a7b7cbc,0.0,9,1,1
9,1d893dd7ca5f77ebf5f59f0d2017eee0,0.0,10,1,1
10,d5fbeedc85190ba88580d6f82d1d5ed3,0.0,11,1,1
11,8339b608be0d84fca9d8da68b58332c3,0.0,12,1,1
12,79e324907160caea526fd8b94389dbbc,0.0,13,1,1
13,25748e98d2de92b6a05bfc40fc2deb9c,1.0,14,14,2
14,be7d02ed4f9ec9a43ac0f6adade17ade,1.0,15,14,2
15,f80e68b525d4ea7025db2f4648d4007d,1.0,16,14,2
16,0cc4f59df564ec8dd6539dfdd8b29472,1.0,17,14,2
17,85b1e09d7a230790544ffb86902bf77b,1.0,18,14,2
18,58df776da444438e064d1e4910f8be87,1.0,19,14,2
19,6a840170ff9f5c99f069b8526d8c21a9,1.0,20,14,2

In [ ]:
WITH pedidos_ranked AS (
    -- Aquí va una query COMPLETA
    SELECT
        o.order_id,
        c.customer_state,
        o.delivery_days,
        ROW_NUMBER() OVER (
            PARTITION BY c.customer_state
            ORDER BY o.delivery_days DESC NULLS LAST
        ) AS ranking_en_estado
    FROM orders o
    LEFT JOIN customers c ON o.customer_id = c.customer_id
)
SELECT *
FROM pedidos_ranked
WHERE ranking_en_estado <= 3;

In [39]:
%%sql
-- Top 3 ciudades con más pedidos por estado, mostrando el total de pedidos de cada ciudad
WITH ciudades_contadas AS (
    -- Paso 1: contar pedidos por ciudad
    SELECT
        c.customer_state,
        c.customer_city,
        COUNT(*) AS total_pedidos
    FROM orders o
    LEFT JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY c.customer_state, c.customer_city
),
ciudades_ranked AS (
    -- Paso 2: añadir el ranking
    SELECT
        customer_state,
        customer_city,
        total_pedidos,
        DENSE_RANK() OVER (
            PARTITION BY customer_state
            ORDER BY total_pedidos DESC
        ) AS ranking
    FROM ciudades_contadas
)
-- Paso 3: filtrar top 3
SELECT *
FROM ciudades_ranked
WHERE ranking <= 3
ORDER BY customer_state, ranking;

   customer_state     customer_city  total_pedidos  ranking
0              AC        rio branco             69        1
1              AC   cruzeiro do sul              3        2
2              AC  senador guiomard              2        3
3              AC            xapuri              2        3
4              AL            maceio            236        1
..            ...               ...            ...      ...
77             SP          campinas           1406        2
78             SP         guarulhos           1144        3
79             TO            palmas             88        1
80             TO         araguaina             38        2
81             TO            gurupi             24        3

[82 rows x 4 columns]

In [28]:
%%sql
SELECT
    c.customer_state,
    c.customer_city,
    COUNT(*) AS total_pedidos
FROM orders o
LEFT JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_state, c.customer_city
ORDER BY c.customer_state, total_pedidos DESC
LIMIT 20;

   customer_state           customer_city  total_pedidos
0              AC              rio branco             69
1              AC         cruzeiro do sul              3
2              AC        senador guiomard              2
3              AC                  xapuri              2
4              AC          epitaciolandia              1
5              AC           manoel urbano              1
6              AC               brasileia              1
7              AC              porto acre              1
8              AL                  maceio            236
9              AL               arapiraca             29
10             AL     palmeira dos indios              8
11             AL                  penedo              8
12             AL         teotonio vilela              7
13             AL               rio largo              6
14             AL                maragogi              5
15             AL         delmiro gouveia              4
16             AL  olho d'agua das flores              3
17             AL                 batalha              3
18             AL                   pilar              3
19             AL                coruripe              3

In [41]:
%%sql
-- Ver columnas y tipos de la tabla orders
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'orders'
ORDER BY ordinal_position;

                     column_name                    data_type
0                       order_id                         text
1                    customer_id                         text
2                   order_status                         text
3       order_purchase_timestamp  timestamp without time zone
4              order_approved_at  timestamp without time zone
5   order_delivered_carrier_date  timestamp without time zone
6  order_delivered_customer_date  timestamp without time zone
7  order_estimated_delivery_date  timestamp without time zone
8                  delivery_days             double precision

In [51]:
%%sql
SELECT
CASE
    WHEN delivery_days < 7 THEN 'rapido'
    WHEN delivery_days BETWEEN 7 AND 20 THEN 'normal'
    WHEN delivery_days > 20 THEN 'lento'
    END AS rango_entrega,
    count(*) as total_pedidos
from orders
GROUP BY rango_entrega
order by total_pedidos DESC

  rango_entrega  total_pedidos
0        normal          57926
1        rapido          26045
2         lento          12499
3          None              8

In [67]:
%%sql
select order_id, delivery_days
    from orders
    where delivery_days >
(
    select AVG(delivery_days)
from orders
)

                               order_id  delivery_days
0      53cdb2fc8bc7dce0b6741e2150273451           13.0
1      949d5b44dbf5de918fe9c16f97b45f8a           13.0
2      a4591c265e18cb1dcee52889e2d8acc3           16.0
3      e69bfb5eb88e0ed6a785585b27e16dbf           18.0
4      dcb36b511fcac050b97cd5c05de84dc3           13.0
...                                 ...            ...
34583  cfa78b997e329a5295b4ee6972c02979           37.0
34584  9115830be804184b91f5c00f6f49f92d           16.0
34585  63943bddc261676b46f01ca7ac2f7bd8           22.0
34586  83c1379a015df1e13d02aae0204711ab           24.0
34587  11c177c8e97725db2631073c19f07b62           17.0

[34588 rows x 2 columns]

In [66]:
%%sql
--Pedidos que tardaron más que la media global
select AVG(delivery_days)
from orders

         avg
0  12.093604